[versions]
coroutines = "1.10.2"
log4j = "2.25.3"
jackson = "2.20.1"
minecraftauth = "5.0.0"
serializationJson = "1.9.0"
includedBuildName = "3.0.0.Beta11-SNAPSHOT"

[libraries]
kotlinx-serialization-json = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "serializationJson" }
adventure = { group = "org.cloudburstmc.protocol", name = "adventure", version.ref = "includedBuildName" }
bedrock-codec = { group = "org.cloudburstmc.protocol", name = "bedrock-codec", version.ref = "includedBuildName" }
common = { group = "org.cloudburstmc.protocol", name = "common", version.ref = "includedBuildName" }
bedrock-connection = { group = "org.cloudburstmc.protocol", name = "bedrock-connection", version.ref = "includedBuildName" }
kotlinx-coroutines = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version.ref = "coroutines" }
net-raphimc-minecraftauth = { group = "net.raphimc", name = "MinecraftAuth", version.ref = "minecraftauth" }
jackson-databind = { group = "com.fasterxml.jackson.core", name = "jackson-databind", version.ref = "jackson" }
log4j-bom = { group = "org.apache.logging.log4j", name = "log4j-bom", version.ref = "log4j" }
log4j-api = { group = "org.apache.logging.log4j", name = "log4j-api" }
log4j-core = { group = "org.apache.logging.log4j", name = "log4j-core" }

[plugins]